# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Anna <cyber@sysrq.in>

kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: 31z4/tox
    commands:
      - tox run
